/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

import CapaGrafica.RegistroFaltaDocente;

import javax.swing.JOptionPane;
/**
 *
 * @author eze
 */
public class GIU_Admin extends javax.swing.JFrame {

    private  String ciAdminLogueado = "";
    private  String rolAdminLogueado = "";
    private String nombreAdminLogueado = "";
    /**
     * Creates new form GIU_Admin
     */
    public GIU_Admin(String ci, String rol, String nombre) {
        initComponents();
        this.ciAdminLogueado = ci; 
        this.rolAdminLogueado = rol; 
        this.nombreAdminLogueado = nombre;
        txtnombreUsuario.setText(nombreAdminLogueado);
        this.setResizable(false);
    
    this.setLocationRelativeTo(null);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVentanaRegistrar = new javax.swing.JButton();
        btnVentanaAgregarAlumno = new javax.swing.JButton();
        btnAgregarDocente = new javax.swing.JButton();
        txtnombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCerrarsesion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Admin");

        btnVentanaRegistrar.setText("Registrar Falta");
        btnVentanaRegistrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVentanaRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaRegistrarActionPerformed(evt);
            }
        });

        btnVentanaAgregarAlumno.setText("Agregar Alumno");
        btnVentanaAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaAgregarAlumnoActionPerformed(evt);
            }
        });

        btnAgregarDocente.setText("Agregar Docente");
        btnAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocenteActionPerformed(evt);
            }
        });

        txtnombreUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtnombreUsuario.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnVentanaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVentanaAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnombreUsuario))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentanaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentanaAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        menuCerrarsesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\ezequ\\Downloads\\menu_16dp_000000_FILL0_wght400_GRAD0_opsz20.png")); // NOI18N
        menuCerrarsesion.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ezequ\\Downloads\\logout_16dp_000000_FILL0_wght400_GRAD0_opsz20.png")); // NOI18N
        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCerrarsesion.add(jMenuItem1);

        menuSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\ezequ\\Downloads\\close_16dp_000000_FILL0_wght400_GRAD0_opsz20.png")); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuCerrarsesion.add(menuSalir);

        jMenuBar1.add(menuCerrarsesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaRegistrarActionPerformed
        String ciAdmin = this.ciAdminLogueado;
        String rolAdmin = this.rolAdminLogueado;

    
    RegistroFaltaDocente ventanaFaltas = new RegistroFaltaDocente(ciAdmin, rolAdmin,nombreAdminLogueado);
    
    ventanaFaltas.setVisible(true);
    }//GEN-LAST:event_btnVentanaRegistrarActionPerformed

    private void btnVentanaAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaAgregarAlumnoActionPerformed

        AgregarAlumno ventanaAlumno = new AgregarAlumno(ciAdminLogueado,rolAdminLogueado, nombreAdminLogueado);
        ventanaAlumno.setVisible(true);
        
    }//GEN-LAST:event_btnVentanaAgregarAlumnoActionPerformed

    private void btnAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocenteActionPerformed
        AgregarDocente ventanaAgregardocente = new AgregarDocente(ciAdminLogueado,rolAdminLogueado, nombreAdminLogueado);
        ventanaAgregardocente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarDocenteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this,
        "¿Está seguro que desea cerrar la sesión actual?", 
        "Confirmar Cierre de Sesión", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose(); 
        
        
        GIU_LOGIN login = new GIU_LOGIN();
        login.setVisible(true);
        
    }    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this,
        "¿Está seguro que desea cerrar el programa por completo?", 
        "Confirmar Salida", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE); 

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }    }//GEN-LAST:event_menuSalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnVentanaAgregarAlumno;
    private javax.swing.JButton btnVentanaRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCerrarsesion;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JLabel txtnombreUsuario;
    // End of variables declaration//GEN-END:variables
}
